// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakan.Domain.Models;

public partial class Amenity
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    public string IconUrl { get; set; }

    [ForeignKey("AmenityId")]
    [InverseProperty("Amenities")]
    public virtual ICollection<Listing> Listings { get; set; } = new List<Listing>();
}