// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakan.Domain.Models;

public partial class Bed
{
    public int Id { get; set; }

    public int? RoomId { get; set; }

    public string Label { get; set; }

    public string Type { get; set; }

    public decimal? Price { get; set; }

    public bool? IsAvailable { get; set; }

    public string OccupiedByUserId { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<BedPhoto> BedPhotos { get; set; } = new List<BedPhoto>();

    public virtual ICollection<BookingRequest> BookingRequests { get; set; } = new List<BookingRequest>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ApplicationUser OccupiedByUser { get; set; }

    public virtual Room Room { get; set; }
}