// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakan.Domain.Models;

public partial class BedPhoto
{
    [Key]
    public int Id { get; set; }

    public int? BedId { get; set; }

    [StringLength(255)]
    public string PhotoUrl { get; set; }

    [ForeignKey("BedId")]
    [InverseProperty("BedPhotos")]
    public virtual Bed Bed { get; set; }
}