// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakan.Domain.Models;

public partial class Booking
{
    public int Id { get; set; }

    public string GuestId { get; set; }

    public int? ListingId { get; set; }

    public int? RoomId { get; set; }

    public int? BedId { get; set; }

    public DateTime FromDate { get; set; }

    public DateTime ToDate { get; set; }

    public decimal? Price { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Bed Bed { get; set; }

    public virtual AspNetUser Guest { get; set; }

    public virtual Listing Listing { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Room Room { get; set; }
}