// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakan.Domain.Models;

public partial class Favorite
{
    public string UserId { get; set; }

    public int ListingId { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual Listing Listing { get; set; }

    public virtual ApplicationUser User { get; set; }
}