// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakan.Domain.Models;

[PrimaryKey("UserId", "ListingId")]
public partial class Favorite
{
    [Key]
    public string UserId { get; set; }

    [Key]
    public int ListingId { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("ListingId")]
    [InverseProperty("Favorites")]
    public virtual Listing Listing { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Favorites")]
    public virtual AspNetUser User { get; set; }
}