// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakan.Domain.Models;

public partial class ListingPhoto
{
    public int Id { get; set; }

    public int? ListingId { get; set; }

    public string PhotoUrl { get; set; }

    public virtual Listing Listing { get; set; }
}