// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakan.Domain.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public string SenderId { get; set; }

    public string ReceiverId { get; set; }

    public string Content { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual ApplicationUser Receiver { get; set; }

    public virtual ApplicationUser Sender { get; set; }
}