// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakan.Domain.Models;

public partial class Notification
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Message { get; set; }

    public bool IsRead { get; set; }

    public string Link { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ApplicationUser User { get; set; }
}