// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakan.Domain.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public string ReviewerId { get; set; }

    public string ReviewedUserId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ApplicationUser ReviewedUser { get; set; }

    public virtual ApplicationUser Reviewer { get; set; }
}