// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakan.Domain.Models;

public partial class SupportTicket
{
    [Key]
    public int Id { get; set; }

    [StringLength(450)]
    public string UserId { get; set; }

    [StringLength(200)]
    public string GuestName { get; set; }

    [StringLength(200)]
    public string GuestEmail { get; set; }

    [Required]
    [StringLength(250)]
    public string Subject { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    [StringLength(50)]
    public string Category { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [Required]
    [StringLength(50)]
    public string Priority { get; set; }

    public int? BookingId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastUpdatedAt { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("SupportTickets")]
    public virtual Booking Booking { get; set; }

    [InverseProperty("SupportTicket")]
    public virtual ICollection<TicketReply> TicketReplies { get; set; } = new List<TicketReply>();

    [ForeignKey("UserId")]
    [InverseProperty("SupportTickets")]
    public virtual AspNetUser User { get; set; }
}