// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakan.Domain.Models;

public partial class TicketReply
{
    public int Id { get; set; }

    public int SupportTicketId { get; set; }

    public string? AuthorId { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual  ApplicationUser Author { get; set; }

    public virtual SupportTicket SupportTicket { get; set; }
}