// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakan.Domain.Models;

public partial class TicketReply
{
    [Key]
    public int Id { get; set; }

    public int SupportTicketId { get; set; }

    [Required]
    [StringLength(450)]
    public string AuthorId { get; set; }

    [Required]
    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("TicketReplies")]
    public virtual AspNetUser Author { get; set; }

    [ForeignKey("SupportTicketId")]
    [InverseProperty("TicketReplies")]
    public virtual SupportTicket SupportTicket { get; set; }
}